/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClassManage;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Muiz
 */
public class AuthorityWindow3 extends javax.swing.JFrame {

    private String userName;
    private String companyID;
    private String Busname;
    private String busID;
    private String assistantID;
    private String driverID;
    private String AllBuses = "\n   Information Of All Buses: \n";
    private String AllDrivers = "\n   Information Of All Drivers: \n";
    private String AllAssistants = "\n   Information Of All Assistants: \n";
    
    Date date = Calendar.getInstance().getTime();  
    DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");  
    DateFormat dateFormat2 = new SimpleDateFormat("hh:mm:ss");  
    String strDate = dateFormat.format(date);
    String strtime = dateFormat2.format(date);

    private String time;
    private Connection con;

    
  
    public AuthorityWindow3(String name,String bname, String cid) {
        this.userName = name;
        this.Busname =  bname;
        this.companyID = cid;
        
        initComponents();
        AllBusInfo();
        AllDriverInfo();
        AllAssistantInfo();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/photo/bus-icon-17.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        username_txt = new javax.swing.JLabel();
        logout_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        DriverEdit_btn = new javax.swing.JButton();
        DriverDelete_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        driverIDText = new javax.swing.JTextField();
        assistantIDText = new javax.swing.JTextField();
        AssEdit_btn = new javax.swing.JButton();
        AssDelete_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        busIDText = new javax.swing.JTextField();
        BusEdit_btn = new javax.swing.JButton();
        BusDelete_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AllAssistant_txt = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        AllBusText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        AllDriver_txt = new javax.swing.JTextArea();
        NewDriver_btn = new javax.swing.JButton();
        NewAss_btn = new javax.swing.JButton();
        NewBus_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Authority Window");

        jPanel1.setBackground(new java.awt.Color(102, 0, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(102, 0, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/bus-icon-26.png"))); // NOI18N
        jLabel4.setOpaque(true);

        username_txt.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        username_txt.setForeground(new java.awt.Color(204, 0, 0));
        username_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username_txt.setText(Busname);

        logout_btn.setText("Logout");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Date: " + strDate);

        jLabel8.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Login time: "+strtime);

        jButton1.setText("See Comments");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(username_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logout_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout_btn)
                .addContainerGap())
        );

        DriverEdit_btn.setText("Edit ");
        DriverEdit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriverEdit_btnActionPerformed(evt);
            }
        });

        DriverDelete_btn.setText("Delete");
        DriverDelete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriverDelete_btnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Driver's ID: ");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Assistant's ID: ");

        AssEdit_btn.setText("Edit ");
        AssEdit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssEdit_btnActionPerformed(evt);
            }
        });

        AssDelete_btn.setText("Delete");
        AssDelete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssDelete_btnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Bus's ID: ");

        BusEdit_btn.setText("Edit ");
        BusEdit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusEdit_btnActionPerformed(evt);
            }
        });

        BusDelete_btn.setText("Delete");
        BusDelete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusDelete_btnActionPerformed(evt);
            }
        });

        AllAssistant_txt.setEditable(false);
        AllAssistant_txt.setColumns(20);
        AllAssistant_txt.setRows(5);
        jScrollPane1.setViewportView(AllAssistant_txt);

        AllBusText.setEditable(false);
        AllBusText.setColumns(20);
        AllBusText.setRows(5);
        jScrollPane2.setViewportView(AllBusText);

        AllDriver_txt.setEditable(false);
        AllDriver_txt.setColumns(20);
        AllDriver_txt.setRows(5);
        jScrollPane3.setViewportView(AllDriver_txt);

        NewDriver_btn.setText(" New Driver");
        NewDriver_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewDriver_btnActionPerformed(evt);
            }
        });

        NewAss_btn.setText(" New Assistant");
        NewAss_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewAss_btnActionPerformed(evt);
            }
        });

        NewBus_btn.setText("New Bus");
        NewBus_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBus_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(driverIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DriverEdit_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DriverDelete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NewDriver_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(assistantIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(AssEdit_btn)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                        .addComponent(busIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BusEdit_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(AssDelete_btn)
                                .addGap(18, 18, 18)
                                .addComponent(NewAss_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BusDelete_btn)
                                .addGap(18, 18, 18)
                                .addComponent(NewBus_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DriverEdit_btn)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(driverIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assistantIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AssEdit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BusEdit_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DriverDelete_btn)
                        .addComponent(NewDriver_btn)
                        .addComponent(AssDelete_btn)
                        .addComponent(NewAss_btn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BusDelete_btn)
                        .addComponent(NewBus_btn)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AllBusInfo(){
                        String url = "jdbc:mysql://localhost/citybusmgnt";
			String userName = "root";
			String pass = "";
                        
                        String bus_id;
                        String licence_plate;
                        String Seat_capacity;
                        String seat_taken;
                        String route_id;
                        String bus_status;
                        String current_location;
                        String driver_id;
                        String assistant_id;
                        String available;
		
			String query1 = "select * from bus where company_id = " + companyID;
			
			
			try
			{
				Class.forName("com.mysql.jdbc.Driver");
				
				con = DriverManager.getConnection(url,userName,pass);
				Statement st = con.createStatement();
				ResultSet rs = st.executeQuery(query1); //retrive driver id
				
                                while(rs.next()){
                                    bus_id = rs.getString(1);
                                    licence_plate = rs.getString(3);
                                    Seat_capacity = rs.getString(4);
                                    seat_taken = rs.getString(5);
                                    route_id = rs.getString(7);
                                    bus_status = rs.getString(8);
                                    current_location = rs.getString(9);
                                    driver_id = rs.getString(10);
                                    assistant_id = rs.getString(11);
                                    available = rs.getString(13);
                                    
                                   AllBuses += "\n Bus ID: " + bus_id
                                            + "\n Licence Plate No.: " + licence_plate
                                            + "\n Seat Capacity: " + Seat_capacity
                                            + "\n Seat Taken: " + seat_taken
                                            + "\n Route ID: " + route_id
                                            + "\n Bus Status: " + bus_status
                                            + "\n Current Location: " + current_location
                                            + "\n Driver ID: " + driver_id
                                            + "\n Assistant ID: " + assistant_id
                                            + "\n Available: " + available + "\n";
                                            
                                    
                                    
                                   AllBusText.setText(AllBuses);
                                }
				con.close();
			}
			catch(Exception ex)
			{
				System.out.println(ex.toString());
			}
    }
    
    
    private void AllDriverInfo(){
                        String url = "jdbc:mysql://localhost/citybusmgnt";
			String userName = "root";
			String pass = "";
                        
                        String driver_id;
                        String licence_plate;
                        String name;
                        String username;
                        String since;
                        String rating;
		
			String query1 = "select d.id, d.Licence_no, e.name, e.username,"
                                + "e.since, e.rating   from driver d, employee e where e.company_id = " + companyID 
                                + " and e.id = d.employee_id";
			
			
			try
			{
				Class.forName("com.mysql.jdbc.Driver");
				
				con = DriverManager.getConnection(url,userName,pass);
				Statement st = con.createStatement();
				ResultSet rs = st.executeQuery(query1); //retrive driver id
				
                                while(rs.next()){
                                    driver_id = rs.getString(1);
                                    licence_plate = rs.getString(2);
                                    name = rs.getString(3);
                                    since = rs.getString(5);
                                    username = rs.getString(4);
                                    rating = rs.getString(6);
                                    
                                    AllDrivers += "\n Driver ID: " + driver_id
                                            + "\n Licence Plate No.: " + licence_plate
                                            + "\n Full Name: " + name
                                            + "\n Username: " + username
                                            + "\n Since: " + since
                                            + "\n Rating: " + rating + "\n";
                                        
                                   AllDriver_txt.setText(AllDrivers);
                                }
				con.close();
			}
			catch(Exception ex)
			{
				System.out.println(ex.toString());
			}
    }
    
    private void AllAssistantInfo(){
                        String url = "jdbc:mysql://localhost/citybusmgnt";
			String userName = "root";
			String pass = "";
                        
                        String assistant_id;
                        String name;
                        String username;
                        String since;
                        String rating;
		
			String query1 = "select a.id, e.name, e.username,"
                                + "e.since, e.rating from assistant a, employee e where e.company_id = " + companyID 
                                + " and e.id = a.employee_id";
                     
			try
			{
				Class.forName("com.mysql.jdbc.Driver");
				
				con = DriverManager.getConnection(url,userName,pass);
				Statement st = con.createStatement();
				ResultSet rs = st.executeQuery(query1);
				
                                while(rs.next()){
                                    assistant_id = rs.getString(1);
                                    name = rs.getString(2);
                                    since = rs.getString(4);
                                    username = rs.getString(3);
                                    rating = rs.getString(5);
                                    
                                    //System.out.println(AllAssistants);
                                   
                                     AllAssistants += "\n Assistant ID: " + assistant_id
                                            + "\n Full Name: " + name
                                            + "\n Username: " + username
                                            + "\n Since: " + since
                                            + "\n Rating: " + rating + "\n";
                                     
                                    AllAssistant_txt.setText(AllAssistants);
                                    
                                    
                                }
                                
				con.close();
			}
			catch(Exception ex)
			{
				System.out.println(ex.toString());
			}
    }
    
    
    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        super.dispose();
        LoginWindow2 lw = new LoginWindow2();
        lw.setLocationRelativeTo(null);
        lw.setVisible(true);
    }//GEN-LAST:event_logout_btnActionPerformed

    private void NewDriver_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewDriver_btnActionPerformed
        super.dispose();
        DriverEntry2 lw = new DriverEntry2(userName, Busname, companyID);
        lw.setLocationRelativeTo(null);
        lw.setVisible(true);
    }//GEN-LAST:event_NewDriver_btnActionPerformed

    private void NewAss_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewAss_btnActionPerformed
        super.dispose();
        AssistantEntry2 lw = new AssistantEntry2(userName, Busname, companyID);
        lw.setLocationRelativeTo(null);
        lw.setVisible(true);
    }//GEN-LAST:event_NewAss_btnActionPerformed

    private void NewBus_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBus_btnActionPerformed
        super.dispose();
        BusEntry2 lw = new BusEntry2(userName, Busname, companyID);
        lw.setLocationRelativeTo(null);
        lw.setVisible(true);
    }//GEN-LAST:event_NewBus_btnActionPerformed

    private void DriverEdit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriverEdit_btnActionPerformed
        driverID = driverIDText.getText();
        super.dispose();
        DriverEdit lw = new DriverEdit(userName, Busname, companyID, driverID);
        lw.setLocationRelativeTo(null);
        lw.setVisible(true);
    }//GEN-LAST:event_DriverEdit_btnActionPerformed

    private void DriverDelete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriverDelete_btnActionPerformed
                        String url = "jdbc:mysql://localhost/citybusmgnt";
			String userName = "root";
			String pass = "";
			String empID;
			
			driverID = driverIDText.getText();
			//System.out.println(driverID);
			
			String query ;
			String query1 = "select employee_id from driver where id = " + driverID;
			String query2;
			
			try
			{
				Class.forName("com.mysql.jdbc.Driver");
				
				con = DriverManager.getConnection(url,userName,pass);
				Statement st = con.createStatement();
				ResultSet rs = st.executeQuery(query1); //retrive driver id
				rs.next();
				empID = rs.getString(1);
				
				//System.out.println(empID);
				query = "delete from employee where id = " + empID; //delete employee from employee table
				st.executeUpdate(query);
								
				query2 = "delete from driver where employee_id = " + empID; // delete from driver
				st.executeUpdate(query2);
				
				con.close();
			}
			catch(Exception ex)
			{
				System.out.println(ex.toString());
			}
    }//GEN-LAST:event_DriverDelete_btnActionPerformed

    private void BusDelete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusDelete_btnActionPerformed
                        String url = "jdbc:mysql://localhost/citybusmgnt";
			String userName = "root";
			String pass = "";
			
			busID = busIDText.getText();
			
			String query = "delete from bus where id = " + busID;
			
			System.out.println(busID);
			try
			{
				Class.forName("com.mysql.jdbc.Driver");
				
				con = DriverManager.getConnection(url,userName,pass);
				Statement st = con.createStatement();
				st.executeUpdate(query);
				
				con.close();
			}
			catch(Exception ex)
			{
				System.out.println(ex.toString());
			}
    }//GEN-LAST:event_BusDelete_btnActionPerformed

    private void AssDelete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssDelete_btnActionPerformed
                        String url = "jdbc:mysql://localhost/citybusmgnt";
			String userName = "root";
			String pass = "";
			String empID;
			
			assistantID = assistantIDText.getText();
			//System.out.println(driverID);
			
			String query ;
			String query1 = "select employee_id from assistant where id = " + assistantID;
			String query2;
			
			try
			{
				Class.forName("com.mysql.jdbc.Driver");
				
				con = DriverManager.getConnection(url,userName,pass);
				Statement st = con.createStatement();
				ResultSet rs = st.executeQuery(query1); //retrive driver id
				rs.next();
				empID = rs.getString(1);
				
				query = "delete from employee where id = " + empID; //delete employee from employee table
				st.executeUpdate(query);
								
				query2 = "delete from assistant where employee_id = " + empID; // delete from driver
				st.executeUpdate(query2);
				
				con.close();
			}
			catch(Exception e)
			{
				System.out.println(e.toString());
			}
    }//GEN-LAST:event_AssDelete_btnActionPerformed

    private void BusEdit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusEdit_btnActionPerformed
        busID = busIDText.getText();
        super.dispose();
        BusEdit lw = new BusEdit(userName, Busname, companyID, busID);
        lw.setLocationRelativeTo(null);
        lw.setVisible(true);
    }//GEN-LAST:event_BusEdit_btnActionPerformed

    private void AssEdit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssEdit_btnActionPerformed
        assistantID = assistantIDText.getText();
        super.dispose();
        AssistantEdit lw = new AssistantEdit(userName, Busname, companyID, assistantID);
        lw.setLocationRelativeTo(null);
        lw.setVisible(true);
    }//GEN-LAST:event_AssEdit_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        super.dispose();
        ComplainWindow lw = new ComplainWindow(userName, Busname, companyID);
        lw.setLocationRelativeTo(null);
        lw.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void getConnection() //with data processing
	{
		
	}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(AuthorityWindow3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(AuthorityWindow3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(AuthorityWindow3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(AuthorityWindow3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            //</editor-fold>

            //</editor-fold>

            //</editor-fold>

            /* Create and display the form */


            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    //new srcDesDecide2("aa","").setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AllAssistant_txt;
    private javax.swing.JTextArea AllBusText;
    private javax.swing.JTextArea AllDriver_txt;
    private javax.swing.JButton AssDelete_btn;
    private javax.swing.JButton AssEdit_btn;
    private javax.swing.JButton BusDelete_btn;
    private javax.swing.JButton BusEdit_btn;
    private javax.swing.JButton DriverDelete_btn;
    private javax.swing.JButton DriverEdit_btn;
    private javax.swing.JButton NewAss_btn;
    private javax.swing.JButton NewBus_btn;
    private javax.swing.JButton NewDriver_btn;
    private javax.swing.JTextField assistantIDText;
    private javax.swing.JTextField busIDText;
    private javax.swing.JTextField driverIDText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton logout_btn;
    private javax.swing.JLabel username_txt;
    // End of variables declaration//GEN-END:variables
}
